import type { Component } from 'vue'
import {
  FolderOutline,
  CartOutline,
  ShirtOutline,
  HardwareChipOutline,
  NutritionOutline,
  CameraOutline,
  GameControllerOutline,
  BookOutline,
  MusicalNotesOutline,
  FitnessOutline,
  HeartOutline,
  StarOutline,
  FlashlightOutline,
  ColorPaletteOutline,
  CubeOutline,
  DiamondOutline,
  HomeOutline,
  CarOutline,
  WalkOutline,
  AirplaneOutline,
  PawOutline,
  LeafOutline,
  FlameOutline,
  WaterOutline,
  SunnyOutline,
  MoonOutline,
  CloudyOutline,
  UmbrellaOutline,
  GiftOutline,
  SparklesOutline,
  TrophyOutline,
  WineOutline,
  CafeOutline,
  PizzaOutline,
  MedicalOutline,
  WalletOutline,
  KeyOutline,
  LockClosedOutline,
  GlobeOutline,
  MapOutline,
  TimeOutline,
  BoatOutline,
  BeerOutline,
  BugOutline,
  FishOutline,
  BulbOutline,
  ExtensionPuzzleOutline,
  RibbonOutline,
} from '@vicons/ionicons5'

export const categoryIconMap: Record<string, Component> = {
  FolderOutline,
  CartOutline,
  ShirtOutline,
  HardwareChipOutline,
  NutritionOutline,
  CameraOutline,
  GameControllerOutline,
  BookOutline,
  MusicalNotesOutline,
  FitnessOutline,
  HeartOutline,
  StarOutline,
  FlashlightOutline,
  ColorPaletteOutline,
  CubeOutline,
  DiamondOutline,
  HomeOutline,
  CarOutline,
  WalkOutline,
  AirplaneOutline,
  PawOutline,
  LeafOutline,
  FlameOutline,
  WaterOutline,
  SunnyOutline,
  MoonOutline,
  CloudyOutline,
  UmbrellaOutline,
  GiftOutline,
  SparklesOutline,
  TrophyOutline,
  WineOutline,
  CafeOutline,
  PizzaOutline,
  MedicalOutline,
  WalletOutline,
  KeyOutline,
  LockClosedOutline,
  GlobeOutline,
  MapOutline,
  TimeOutline,
  BoatOutline,
  BeerOutline,
  BugOutline,
  FishOutline,
  BulbOutline,
  ExtensionPuzzleOutline,
  RibbonOutline,
}

/**
 * 可选图标清单。**刻意不带 label 字段** —— tooltip 文案走
 * `t('app.icons.<组件名>')` 在模板里查语言包。
 *
 * 把 48 条中文写在这里，等于同一份文案在语言包之外又存了一份，翻译时必然漏掉这一处；
 * 键直接取组件名，也不会有对不上的风险（重命名图标时编译器会提醒）。
 */
export const categoryIconOptions: { name: string }[] = [
  { name: 'FolderOutline' },
  { name: 'CartOutline' },
  { name: 'ShirtOutline' },
  { name: 'HardwareChipOutline' },
  { name: 'NutritionOutline' },
  { name: 'CameraOutline' },
  { name: 'GameControllerOutline' },
  { name: 'BookOutline' },
  { name: 'MusicalNotesOutline' },
  { name: 'FitnessOutline' },
  { name: 'HeartOutline' },
  { name: 'StarOutline' },
  { name: 'FlashlightOutline' },
  { name: 'ColorPaletteOutline' },
  { name: 'CubeOutline' },
  { name: 'DiamondOutline' },
  { name: 'HomeOutline' },
  { name: 'CarOutline' },
  { name: 'WalkOutline' },
  { name: 'AirplaneOutline' },
  { name: 'BoatOutline' },
  { name: 'PawOutline' },
  { name: 'LeafOutline' },
  { name: 'FlameOutline' },
  { name: 'WaterOutline' },
  { name: 'SunnyOutline' },
  { name: 'MoonOutline' },
  { name: 'CloudyOutline' },
  { name: 'UmbrellaOutline' },
  { name: 'GiftOutline' },
  { name: 'SparklesOutline' },
  { name: 'TrophyOutline' },
  { name: 'WineOutline' },
  { name: 'CafeOutline' },
  { name: 'PizzaOutline' },
  { name: 'MedicalOutline' },
  { name: 'WalletOutline' },
  { name: 'KeyOutline' },
  { name: 'LockClosedOutline' },
  { name: 'GlobeOutline' },
  { name: 'MapOutline' },
  { name: 'TimeOutline' },
  { name: 'BeerOutline' },
  { name: 'BugOutline' },
  { name: 'FishOutline' },
  { name: 'BulbOutline' },
  { name: 'ExtensionPuzzleOutline' },
  { name: 'RibbonOutline' },
]

export function getCategoryIcon(name?: string): Component {
  return categoryIconMap[name ?? 'FolderOutline'] ?? FolderOutline
}

export const categoryColors: string[] = [
  '#f59e0b',
  '#ef4444',
  '#3b82f6',
  '#10b981',
  '#8b5cf6',
  '#ec4899',
  '#14b8a6',
  '#f97316',
  '#64748b',
]
