import type { Component } from 'vue'
import {
  FolderOutline,
  CartOutline,
  ShirtOutline,
  HardwareChipOutline,
  NutritionOutline,
  CameraOutline,
  GameControllerOutline,
  BookOutline,
  MusicalNotesOutline,
  FitnessOutline,
  HeartOutline,
  StarOutline,
  FlashlightOutline,
  ColorPaletteOutline,
  CubeOutline,
  DiamondOutline,
  HomeOutline,
  CarOutline,
  WalkOutline,
  AirplaneOutline,
  PawOutline,
  LeafOutline,
  FlameOutline,
  WaterOutline,
  SunnyOutline,
  MoonOutline,
  CloudyOutline,
  UmbrellaOutline,
  GiftOutline,
  SparklesOutline,
  TrophyOutline,
  WineOutline,
  CafeOutline,
  PizzaOutline,
  MedicalOutline,
  WalletOutline,
  KeyOutline,
  LockClosedOutline,
  GlobeOutline,
  MapOutline,
  TimeOutline,
  BoatOutline,
  BeerOutline,
  BugOutline,
  FishOutline,
  BulbOutline,
  ExtensionPuzzleOutline,
  RibbonOutline,
} from '@vicons/ionicons5'

export const categoryIconMap: Record<string, Component> = {
  FolderOutline,
  CartOutline,
  ShirtOutline,
  HardwareChipOutline,
  NutritionOutline,
  CameraOutline,
  GameControllerOutline,
  BookOutline,
  MusicalNotesOutline,
  FitnessOutline,
  HeartOutline,
  StarOutline,
  FlashlightOutline,
  ColorPaletteOutline,
  CubeOutline,
  DiamondOutline,
  HomeOutline,
  CarOutline,
  WalkOutline,
  AirplaneOutline,
  PawOutline,
  LeafOutline,
  FlameOutline,
  WaterOutline,
  SunnyOutline,
  MoonOutline,
  CloudyOutline,
  UmbrellaOutline,
  GiftOutline,
  SparklesOutline,
  TrophyOutline,
  WineOutline,
  CafeOutline,
  PizzaOutline,
  MedicalOutline,
  WalletOutline,
  KeyOutline,
  LockClosedOutline,
  GlobeOutline,
  MapOutline,
  TimeOutline,
  BoatOutline,
  BeerOutline,
  BugOutline,
  FishOutline,
  BulbOutline,
  ExtensionPuzzleOutline,
  RibbonOutline,
}

export const categoryIconOptions: { name: string; label: string }[] = [
  { name: 'FolderOutline', label: '文件夹' },
  { name: 'CartOutline', label: '购物车' },
  { name: 'ShirtOutline', label: '衣物' },
  { name: 'HardwareChipOutline', label: '芯片' },
  { name: 'NutritionOutline', label: '营养' },
  { name: 'CameraOutline', label: '相机' },
  { name: 'GameControllerOutline', label: '游戏' },
  { name: 'BookOutline', label: '书本' },
  { name: 'MusicalNotesOutline', label: '音乐' },
  { name: 'FitnessOutline', label: '健身' },
  { name: 'HeartOutline', label: '心形' },
  { name: 'StarOutline', label: '星形' },
  { name: 'FlashlightOutline', label: '手电' },
  { name: 'ColorPaletteOutline', label: '调色板' },
  { name: 'CubeOutline', label: '立方体' },
  { name: 'DiamondOutline', label: '钻石' },
  { name: 'HomeOutline', label: '家居' },
  { name: 'CarOutline', label: '汽车' },
  { name: 'WalkOutline', label: '步行' },
  { name: 'AirplaneOutline', label: '飞机' },
  { name: 'BoatOutline', label: '船' },
  { name: 'PawOutline', label: '宠物' },
  { name: 'LeafOutline', label: '植物' },
  { name: 'FlameOutline', label: '火焰' },
  { name: 'WaterOutline', label: '水滴' },
  { name: 'SunnyOutline', label: '太阳' },
  { name: 'MoonOutline', label: '月亮' },
  { name: 'CloudyOutline', label: '云朵' },
  { name: 'UmbrellaOutline', label: '雨伞' },
  { name: 'GiftOutline', label: '礼物' },
  { name: 'SparklesOutline', label: '闪光' },
  { name: 'TrophyOutline', label: '奖杯' },
  { name: 'WineOutline', label: '酒杯' },
  { name: 'CafeOutline', label: '咖啡' },
  { name: 'PizzaOutline', label: '披萨' },
  { name: 'MedicalOutline', label: '医疗' },
  { name: 'WalletOutline', label: '钱包' },
  { name: 'KeyOutline', label: '钥匙' },
  { name: 'LockClosedOutline', label: '锁' },
  { name: 'GlobeOutline', label: '地球' },
  { name: 'MapOutline', label: '地图' },
  { name: 'TimeOutline', label: '时间' },
  { name: 'BeerOutline', label: '啤酒' },
  { name: 'BugOutline', label: '昆虫' },
  { name: 'FishOutline', label: '鱼' },
  { name: 'BulbOutline', label: '灯泡' },
  { name: 'ExtensionPuzzleOutline', label: '拼图' },
  { name: 'RibbonOutline', label: '丝带' },
]

export function getCategoryIcon(name?: string): Component {
  return categoryIconMap[name ?? 'FolderOutline'] ?? FolderOutline
}

export const categoryColors: string[] = [
  '#f59e0b',
  '#ef4444',
  '#3b82f6',
  '#10b981',
  '#8b5cf6',
  '#ec4899',
  '#14b8a6',
  '#f97316',
  '#64748b',
]
